name: CP4
version: '${project.version}'
main: cp4.status.CP4Plugin
api-version: 1.19
authors: [ Oasis ]
commands:
  onlinezeit:
    usage: /Onlinezeit
    description: Schau dir deine Onlinezeit an
  afk:
    usage: /Afk
    description: Du Bekommst die Rolle AFK
  sub:
    usage: /sub
  flame:
    usage: /flame
    aliases: [f]
  live:
    usage: /Live
    aliases:
      - l
  reset:
    usage: /reset
    aliases:
      - r
  oasislive:
    usage: /oasislive
    aliases:
      - ol
  rw:
    usage: /rw

depend:
  - LuckPerms

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20-RC


