name: CraftProtect
version: '${project.version}'
main: com.github.oasis.craftprotect.CraftProtectPlugin
api-version: 1.19
authors: [ Oasis, LeBaasti, CyntrixAlgorithm ]
softdepend:
  - LuckPerms

folia-supported: true

libraries:
  - org.apache.commons:commons-text:1.10.0
  - io.netty:netty-all:4.1.90.Final
  - com.github.twitch4j:twitch4j:1.15.0
  - io.reactivex.rxjava3:rxjava:3.1.6
  - de.javagl:obj:0.4.0
  - com.google.inject:guice:7.0.0
  - org.mariadb.jdbc:mariadb-java-client:3.1.4