name: CraftProtect
version: '${project.version}'
main: com.github.oasis.craftprotect.CraftProtectPlugin
api-version: 1.19
authors: [ Oasis, LeBaasti, CyntrixAlgorithm ]
commands:
  onlinezeit:
    usage: /onlinezeit
    description: Benutze diesen Befehl, um dir deine Spielzeit anzuschauen.
  afk:
    usage: /afk
    description: Wenn du diesen Befehl ausführst, bekommst du die Rolle AFK
  sub:
    usage: /sub
  flame:
    usage: /flame
    permission: craftprotect.command.flame
    aliases: [f]
  live:
    usage: /Live
    aliases:
      - l
  reset:
    usage: /reset
    aliases:
      - r
  oasislive:
    usage: /oasislive
    aliases:
      - ol
  rw:
    usage: /rw

depend:
  - LuckPerms

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20-RC
  - org.apache.commons:commons-text:1.10.0


